[ALPS07673475] bt: fix build errors against kernel-5.18
Fix build breaks introduced in v5.18 merge.

vendor/mediatek/kernel_modules/connectivity/bt/linux_v2/uart/btmtktty.c:1633:44: error: too many arguments to function call, expected 3, have 4
vendor/mediatek/kernel_modules/connectivity/bt/linux_v2/uart/btmtktty.c:1717:44: error: too many arguments to function call, expected 3, have 4
vendor/mediatek/kernel_modules/connectivity/bt/linux_v2/uart/btmtktty.c:2231:25: error: incompatible function pointer types assigning to int (*)(struct tty_struct *, unsigned int, unsigned long) from int (struct tty_struct *, struct file *, unsigned int, unsigned long) [-Werror,-Wincompatible-function-pointer-types]
vendor/mediatek/kernel_modules/connectivity/bt/linux_v2/uart/btmtktty.c:2232:32: error: incompatible function pointer types assigning to int (*)(struct tty_struct *, unsigned int, unsigned long) from int (struct tty_struct *, struct file *, unsigned int, unsigned long) [-Werror,-Wincompatible-function-pointer-types]

MTK-Commit-Id: 2d6b48f6b8147ad3e87047a0164d0f015767a32e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Idef93b10178695246c379af08e73cfa631f1984d