[ALPS07673475] gpu: fix local_clock build breaks
Fix local_clock by including linux/sched/clock.h

vendor/mediatek/kernel_modules/gpu/mt6983/mali_valhall/mali-r38p0/drivers/gpu/arm/midgard/platform/mtk_platform_common/mtk_platform_logbuffer.c:106:21: error: implicit declaration of function local_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/gpu/mt6886/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/platform/mtk_platform_common/mtk_platform_logbuffer.c:106:21: error: implicit declaration of function local_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/platform/mtk_platform_common/mtk_platform_logbuffer.c:106:21: error: implicit declaration of function local_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/gpu/mt6983/mali_valhall/mali-r38p0/drivers/gpu/arm/midgard/csf/mali_kbase_csf_firmware_cfg.c:216:3: error: field designator default_attrs does not refer to any field in type struct kobj_type

MTK-Commit-Id: 168dc74e8c65ad65ecef43fff1ba9ea4fd158d88

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ia3e3f8abfc61d501da0b9e2a115fb63aede51de5