[ALPS07673475] wmt: use rtnl_link_stats64
commit 625788b58445 ("net: add per-cpu storage and net->core_stats")
removed rx_dropped, use rtnl_link_stats64 to read the core counter
and fix the following build breaks

Errors:
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/
gl_kal.c:9595:30: error: no member named tx_dropped in
struct net_device
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/
gl_kal.c:9598:30: error: no member named rx_dropped in
struct net_device

MTK-Commit-Id: f1e01cdeac43b04e0560ee4a35d1d6f6de276c08

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I59adbefd28396dfd2622579f55c28ace62708eb3
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6675501
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
CheckCourse: srv_pis <srv_pis@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Reviewed-by: tf.huang <tf.huang@mediatek.com>
Reviewed-by: deren.wu <deren.wu@mediatek.com>
Test: srv_pf_nep_sanity
CheckSWIP: srv_pis <srv_pis@mediatek.com>
CheckPatch: srv_pis <srv_pis@mediatek.com>
Test: srv_mspautosanity