[ALPS07713407] wlan: fix thermal_zone_of_device_ops build breaks
Follow commit f59ac19b7f44 ("thermal/of: Remove old OF code") to
move to new OF APIs and fix the following build breaks:

wlan/core/gen4m/os/linux/gl_kal.c:13579:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
wlan/core/gen4m/os/linux/gl_kal.c:13605:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
wlan/core/gen4m/os/linux/gl_kal.c:13646:3: error: call to undeclared function devm_thermal_zone_of_sensor_unregister; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
wlan/core/gen4m/os/linux/gl_kal.c:13579:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
wlan/core/gen4m/os/linux/gl_kal.c:13605:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
wlan/core/gen4m/os/linux/gl_kal.c:13646:3: error: call to undeclared function devm_thermal_zone_of_sensor_unregister; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 313c81c6464a071bed90009ab142e6aff1a96e9f

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: If7ad5a005cba0eb8079ad77ba9e364c9e37e61d7
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6793470
CheckCourse: srv_pis <srv_pis@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
CheckPatch: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Test: srv_pf_nep_sanity
Reviewed-by: deren.wu <deren.wu@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
Test: srv_mspautosanity
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
CheckSWIP: srv_pis <srv_pis@mediatek.com>
Reviewed-by: tf.huang <tf.huang@mediatek.com>