[ALPS07673475] wmt: fix get_ether_addr build breaks
Follow commit 99984b081f99 ("usb: gadget: u_ether: use eth_hw_addr_set()")
to fix the following build breaks

Errors:
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_cfg80211.c:6606:14: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_cfg80211.c:6606:14:/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_22_13_00-mainline/merged/kernel/../vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_p2p.c:1370:14: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_init.c:2655:16: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_init.c:5770:16: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:944:10: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_nan.c:763:13: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_nan.c:781:31: error: passing const unsigned char * to parameter of type uint8_t * (aka unsigned char *) discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_p2p.c:1370:14: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_p2p.c:2312:16: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_p2p_cfg80211.c:448:14: error: passing const unsigned char * to parameter of type void * discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

MTK-Commit-Id: a308387b70b8b1ab4fb091216146d00cc279f201

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I1d63bc33193bd02ad001c35e190e9ae1dbda5271
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6675498
Reviewed-by: tf.huang <tf.huang@mediatek.com>
Test: srv_mspautosanity
CheckPatch: srv_pis <srv_pis@mediatek.com>
CheckSWIP: srv_pis <srv_pis@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Reviewed-by: deren.wu <deren.wu@mediatek.com>
CheckCourse: srv_pis <srv_pis@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
Test: srv_pf_nep_sanity