[ALPS07713407] wlan: fix netif_napi_add build breaks
Follow commit b48b89f9c189 ("net: drop the weight argument from netif_napi_add")
to remove the weight from netif_napi_add to fix the following build
breaks:

wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4
wlan/core/gen4m/os/linux/gl_kal.c:12148:16: error: too many arguments to function call, expected 3, have 4

MTK-Commit-Id: e1a3c6cb2b82a7d7723bd4e316d7fb50a00f16db

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I3ea8a54540f5d9b9dbbb4518f620642538f423bd
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6793469
Test: srv_pf_nep_sanity
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
CheckCourse: srv_pis <srv_pis@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
Test: srv_mspautosanity
CheckSWIP: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
Reviewed-by: deren.wu <deren.wu@mediatek.com>
Reviewed-by: tf.huang <tf.huang@mediatek.com>