[ALPS07673475] wmt: pci_dma breaks
Follow commit a2e759612e5f ("mt76: switch from pci_ to dma_ API") to
fix the following build breaks by using the sed command below:

s/PCI_DMA_BIDIRECTIONAL/DMA_BIDIRECTIONAL/g
s/PCI_DMA_TODEVICE/DMA_TO_DEVICE/g
s/PCI_DMA_FROMDEVICE/DMA_FROM_DEVICE/g
s/PCI_DMA_NONE/DMA_NONE/g
s/pci_alloc_consistent/dma_alloc_coherent/g
s/pci_zalloc_consistent/dma_alloc_coherent/g
s/pci_free_consistent/dma_free_coherent/g
s/pci_map_single/dma_map_single/g
s/pci_unmap_single/dma_unmap_single/g
s/pci_map_page/dma_map_page/g
s/pci_unmap_page/dma_unmap_page/g
s/pci_map_sg/dma_map_sg/g
s/pci_unmap_sg/dma_unmap_sg/g
s/pci_dma_sync_single_for_cpu/dma_sync_single_for_cpu/g
s/pci_dma_sync_single_for_device/dma_sync_single_for_device/g
s/pci_dma_sync_sg_for_cpu/dma_sync_sg_for_cpu/g
s/pci_dma_sync_sg_for_device/dma_sync_sg_for_device/g
s/pci_dma_mapping_error/dma_mapping_error/g
s/pci_set_dma_mask/dma_set_mask/g
s/pci_set_consistent_dma_mask/dma_set_coherent_mask/g

vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_emi.c:100:2: error: implicit declaration of function pci_free_consistent is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_emi.c:80:13: error: implicit declaration of function pci_alloc_consistent is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1059:8: error: implicit declaration of function pci_set_dma_mask is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1419:10: error: implicit declaration of function pci_map_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1420:29: error: use of undeclared identifier PCI_DMA_FROMDEVICE; did you mean DMA_FROM_DEVICE?
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1421:6: error: implicit declaration of function pci_dma_mapping_error is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1909:22: error: incompatible integer to pointer conversion assigning to void * from int [-Werror,-Wint-conversion]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1909:24: error: implicit declaration of function pci_alloc_consistent is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1950:10: error: implicit declaration of function pci_map_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1951:29: error: use of undeclared identifier PCI_DMA_FROMDEVICE; did you mean DMA_FROM_DEVICE?
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1952:6: error: implicit declaration of function pci_dma_mapping_error is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1979:10: error: implicit declaration of function pci_map_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1980:20: error: use of undeclared identifier PCI_DMA_TODEVICE; did you mean DMA_TO_DEVICE?
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:1981:6: error: implicit declaration of function pci_dma_mapping_error is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2001:2: error: implicit declaration of function pci_unmap_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2003:30: error: use of undeclared identifier PCI_DMA_FROMDEVICE; did you mean DMA_FROM_DEVICE?
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2012:10: error: implicit declaration of function pci_map_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2013:29: error: use of undeclared identifier PCI_DMA_FROMDEVICE; did you mean DMA_FROM_DEVICE?
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2014:6: error: implicit declaration of function pci_dma_mapping_error is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2042:2: error: implicit declaration of function pci_unmap_single is invalid in C99 [-Werror,-Wimplicit-function-declaration]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/hif/pcie/pcie.c:2044:30: error: use of undeclared identifier PCI_DMA_FROMDEVICE; did you mean DMA_FROM_DEVICE?

MTK-Commit-Id: 0bbdc1c7101e0f14199e298536e756fbf9f71cad

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I852ab0cdd4357237c14875478a09227b01b5289e
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6675500
CheckPatch: srv_pis <srv_pis@mediatek.com>
Reviewed-by: tf.huang <tf.huang@mediatek.com>
Test: srv_mspautosanity
Build: srv_pf_nep_win <srv_pf_nep_win@mediatek.com>
Test: srv_pf_nep_sanity
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
Reviewed-by: deren.wu <deren.wu@mediatek.com>
CheckCourse: srv_pis <srv_pis@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Reviewed-by: ch.ko <ch.ko@mediatek.com>
CheckSWIP: srv_pis <srv_pis@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>