[ALPS07673475] wmt: remove netif_rx_ni
Remove netif_rx_ni(), use netif_rx() after the commit 2655926aea9b
("net: Remove netif_rx_any_context() and netif_rx_ni().")

Errors:
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2065:3: error: implicit declaration of function netif_rx_ni is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: df2f33814df21a871316cd329f6c1f9d43b4f064

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Id649ac7efe9b84fd1e112be181207a8eca07f19b
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/6675502
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
CheckPatch: srv_pis <srv_pis@mediatek.com>
Test: srv_pf_nep_sanity
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
CheckSWIP: srv_pis <srv_pis@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_mspautosanity
Reviewed-by: tf.huang <tf.huang@mediatek.com>
Reviewed-by: nina.hsu <nina.hsu@mediatek.com>
CheckCourse: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Reviewed-by: deren.wu <deren.wu@mediatek.com>