[ALPS07713407] gpu: fix rbtree build breaks
Follow commit 0c563f148043 ("proc: remove VMA rbtree use from nommu")
to use maple tree instead of VMA rbtree.

gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:158:18: error: no member named highest_vm_end in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:25: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:166:6: error: invalid operands to binary expression (void and void *)
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:168:21: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:168:21: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:168:21: error: no member named mm_rb in struct mm_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:168:8: error: no member named vm_rb in vm_area_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:168:6: error: assigning to struct vm_area_struct * from incompatible type void
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:169:11: error: no member named rb_subtree_gap in struct vm_area_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:174:20: error: no member named vm_prev in struct vm_area_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:174:35: error: no member named vm_prev in struct vm_area_struct
gpu/mt6985/mali_valhall/mali-r38p1/drivers/gpu/arm/midgard/thirdparty/mali_kbase_mmap.c:175:39: error: no member named vm_rb in struct vm_area_struct
fatal error: too many errors emitted, stopping now [-ferror-limit=]

MTK-Commit-Id: 68652e2dc0d60a588276b6c8ac954a69c9e30cdb

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I242d7c672c1c778dfe7bf759178c9c4405c81607