[WCNCR00310250] misc: Add v6.3 support
[Description]
Add v6.3 support

Header file "linux/sched/clock.h" was removed in commit 9ac849f2c492
("net: skbuff: drop the linux/sched/clock.h include"). gen4m should
include this file in linux gl_kal.h

Fix build fail:
gen4m/os/linux/include/gl_kal.h:1225:41: error: implicit declaration
of function ‘sched_clock’; did you mean ‘sched_fork’?
[-Werror=implicit-function-declaration]
 1225 | #define kalGetTimeTickNs()              sched_clock()
      |                                         ^~~~~~~~~~~

MTK-Commit-Id: 5268aa984990ba9d7386324acaf9b98e29fa1830

Change-Id: I75026b170fe18e4eee07968ec9940543191d94a6
Signed-off-by: Deren Wu <deren.wu@mediatek.com>
CR-Id: WCNCR00310250
Feature: misc
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/7515915
Test: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Reviewed-by: jianling.fu <jianling.fu@mediatek.com>
Build: srv_preflight_b001 <srv_preflight_b001@mediatek.com>
Coverity-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Reviewed-by: soul.huang <soul.huang@mediatek.com>
Commit-Check: srv_pis <srv_pis@mediatek.com>
Test: srv_pf_nep_sanity
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Reviewed-by: wyatt.sun <wyatt.sun@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>